apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- jupyter.yaml

configMapGenerator:
- name: jax-workshop-environment
  files:
  - requirements-workshop.txt
  - verify_environment.py

generatorOptions:
  disableNameSuffixHash: true
